### ISSUE TITLE
inlining failed in call to always_inline

### ISSUE THREAD

**Issue by songzhiye** [Eugnis/spectre-attack#15]
When I compile the source code with the Code::Blocks, I get some errors:
`||=== Build: Debug in Spectre_test (compiler: GNU GCC Compiler) ===|
xxx\main.c||In function 'readMemoryByte':|
xxx\main.c|65|error: 'for' loop initial declarations are only allowed in C99 or C11 mode|
xxx\main.c|65|note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code|
xxx\main.c||In function 'main':|
xxx\main.c|122|error: 'for' loop initial declarations are only allowed in C99 or C11 mode|
||=== Build failed: 2 error(s), 0 warning(s) (0 minute(s), 0 second(s)) ===|`
and then I use  option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile the code, I get some other errors:
`||=== Build: Debug in Spectre_test (compiler: GNU GCC Compiler) ===|
xxx\main.c||In function 'readMemoryByte':|
C:\Program Files (x86)\CodeBlocks\MinGW\lib\gcc\mingw32\4.9.2\include\emmintrin.h|1459|error: inlining failed in call to always_inline '_mm_clflush': target specific option mismatch|
xxx\main.c|58|error: called from here|
C:\Program Files (x86)\CodeBlocks\MinGW\lib\gcc\mingw32\4.9.2\include\emmintrin.h|1459|error: inlining failed in call to always_inline '_mm_clflush': target specific option mismatch|
xxx\main.c|64|error: called from here|
||=== Build failed: 4 error(s), 0 warning(s) (0 minute(s), 0 second(s)) ===|`

**Comment by Eugnis** [comment]
Hello. Use `-std=c99` and also add march flag. For example: `-std=c99 -march=core2`

**Comment by songzhiye** [comment]
@Eugnis Thank you! The problem is solved
