### ISSUE TITLE
Mitigations?

### ISSUE THREAD

**Issue by WebLL** [Eugnis/spectre-attack#18]
Would there be any interest in including some potential mitigations for testing and demonstration. I have just written up one that I have not seem mentioned elsewhere and it seems to perform a lot better than the Intel suggestion of lfence. See https://weblll.org/index.php/spectre-bounds-check-data-flow-mitigation/ which has code that works with this demonstration and thank you for writing it.

**Comment by Eugnis** [comment]
Original code is not completely mine and came from [Spectre paper](https://spectreattack.com/spectre.pdf). 
Nice way in your article but I've tried example and have some errors in asm part while compiling with gcc.
```
ccbVyKNV.s:34: Error: invalid instruction suffix for 'sub'
ccbVyKNV.s:36: Error: missing ')'
ccbVyKNV.s:36: Error: junk ')' after expression
```

**Comment by WebLL** [comment]
The code only worked on linux x64. Apparently this is not sufficient, it works much of the time but maybe if speculating on an earlier branch it can delay the later branch resolution and so still access the memory and leak that value.
