### ISSUE TITLE
still vulnerabilities?

### ISSUE THREAD

**Issue by soap70** [Eugnis/spectre-attack#20]
Hello,

i did this:

grep . /sys/devices/system/cpu/vulnerabilities/*
/sys/devices/system/cpu/vulnerabilities/meltdown:Mitigation: PTI
/sys/devices/system/cpu/vulnerabilities/spectre_v1:Mitigation: Barriers
/sys/devices/system/cpu/vulnerabilities/spectre_v2:Mitigation: Full generic retpoline

and run your program an wondered why it is working.

Can you explain this?

Greetinx, Oliver

**Comment by Eugnis** [comment]
Hello. If launch this example without parameters it reads memory records for its own process. 

To test out memory access to another process's records you should pass these parameters `.\spectre.out {address} {length}`  Spectre patches fixes only accessing another process memory so this won't work. 

Anyway reading memory from program own process not blocked with patches.

**Comment by soap70** [comment]
thx for the quick response!

**Comment by soap70** [comment]
thx for the quick answer.
