### ISSUE TITLE
Странное поведение

### ISSUE THREAD

**Issue by egorsmkv** [Eugnis/spectre-attack#3]
@Eugnis привет.

Хочу спросить вот о чём: протестировал твою программу на сервере под CentOS до установки обновлений - программа выдаёт весь текст "The Magic Words are Squeamish Ossifrage.", что является успешным выполнением и подтверждением уязвимости сервера, как я понимаю. Но после установки обновлений текст проверки тоже срабатывает.

Можешь объяснить почему так?

**Comment by alexgdi** [comment]
@egorsmkv  патч исправляет Meltdown, От Spectre он не помогает. Проблему Spectre решить программным способом очень проблематично.
